name: Make Release Builds

on: [workflow_dispatch]

jobs:
  create-new-release:
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    permissions:
      contents: write

    outputs:
      new_tag: ${{ steps.set-release-tag.outputs.new_tag }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: master

      - name: Set release tag and create (empty) release
        id: set-release-tag
        shell: bash
        run: |
          set -euo pipefail

          repo_tags="$(gh api \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              /repos/${{ github.repository }}/tags)"

          latest_tag="$(jq -r '.[0].name' <<< "$repo_tags")"
          today="$(date +"%Y%m%d")"

          if [ "${latest_tag::-2}" = "$today" ]; then
              new_tag="$((latest_tag+1))"
          else
              new_tag="${today}00"
          fi

          run_url="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          gh release create --notes "Produced by GitHub actions run: ${run_url}" "$new_tag"
          echo "new_tag=$new_tag" >> "$GITHUB_OUTPUT"

        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos-universal:
    needs: create-new-release
    runs-on: macos-13
    timeout-minutes: 15

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: master

      - name: Compile macOS universal app and upload file to release
        run: |
          ./build-mac-app.sh
          openssl sha256 SpaceCadetPinball-*-mac.dmg
          gh release upload "$NEW_TAG" SpaceCadetPinball-*-mac.dmg

        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEW_TAG: ${{ needs.create-new-release.outputs.new_tag }}

  build-linux-appimage-x86_64:
    needs: create-new-release
    runs-on: ubuntu-22.04
    timeout-minutes: 15

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: master

      - name: Compile Linux x86_64 app and upload file to release
        run: |
          sudo apt update
          sudo apt install -y desktop-file-utils libsdl2-dev libsdl2-mixer-dev
          ./build-linux-app.sh
          openssl sha256 SpaceCadetPinball-*-linux-x86_64.AppImage
          gh release upload "$NEW_TAG" SpaceCadetPinball-*-linux-x86_64.AppImage

        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEW_TAG: ${{ needs.create-new-release.outputs.new_tag }}

  build-linux-appimage-aarch64:
    needs: create-new-release
    runs-on: ubuntu-22.04-arm
    timeout-minutes: 15

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: master

      - name: Compile Linux aarch64 app and upload file to release
        run: |
          sudo apt update
          sudo apt install -y desktop-file-utils libsdl2-dev libsdl2-mixer-dev
          ./build-linux-app.sh
          openssl sha256 SpaceCadetPinball-*-linux-aarch64.AppImage
          gh release upload "$NEW_TAG" SpaceCadetPinball-*-linux-aarch64.AppImage

        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEW_TAG: ${{ needs.create-new-release.outputs.new_tag }}
