name: Make Release Builds

on: [workflow_dispatch]

jobs:
  build-macos-universal:
    runs-on: macos-12
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 13

      - run: ./build-mac-app.sh

      - uses: actions/upload-artifact@v4
        with:
          name: mac-build-universal
          path: SpaceCadetPinball-*-mac.dmg

  build-linux-appimage-x86_64:
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master

      - run: |
          sudo apt update
          sudo apt install -y desktop-file-utils libsdl2-dev libsdl2-mixer-dev

      - run: ./build-linux-app.sh

      - uses: actions/upload-artifact@v4
        with:
          name: linux-build-x86_64
          path: SpaceCadetPinball-*-linux-x86_64.AppImage

  build-linux-appimage-aarch64:
    runs-on: ubuntu-22.04-arm
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master

      - run: |
          sudo apt update
          sudo apt install -y desktop-file-utils libsdl2-dev libsdl2-mixer-dev

      - run: ./build-linux-app.sh

      - uses: actions/upload-artifact@v4
        with:
          name: linux-build-aarch64
          path: SpaceCadetPinball-*-linux-aarch64.AppImage
